version: '3.8'
services:
  dev-database:
    image: mysql:8.0
    container_name: ecommerce-admin
    restart: always
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Abc123456
      MYSQL_DATABASE: ecommerce-admin
#Create container,network,...from "docker composer" file:
#-d: deamon/background mode
#docker compose up -d 
#if you want to start only specified services/container:
#docker compose up -d dev-database -d
#How to remove containers+volumes
#docker compose rm dev-database --stop --force --volumes